runtime: go113

automatic_scaling:
  target_cpu_utilization: 0.80
  max_instances: 1

# deploy.sh will setup the files to have the
# web directory content at the root of the application
env_variables:
  WEB_DIR: "."

handlers:
# Configure App Engine to serve any static assets.
- url: /static
  static_dir: static

# Use HTTPS for all requests.
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto